MVC5_ASP_DOT_NET/Models/LireModel.cs
 
namespace MVC5_ASP_DOT_NET.Models
{
    public class LireModel
    {
        public int ID { get; set; }
        public string Title { get; set; }
    }
}

MVC5_ASP_DOT_NET/Controllers/ArticleController.cs
using MVC5_ASP_DOT_NET.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC5_ASP_DOT_NET.Controllers
{
    public class ArticleController : Controller
    {
        // GET: Article 
        [Route("Lire/{id}/{title}")]
        public ActionResult Lire(int id ,string title )
        {
            //var title = Request.Params["title"];
            /* ViewBag.ArticleID = id;
           if (!string.IsNullOrEmpty(title)) {
                ViewBag.ArticleTitle = title.Replace('-',' ');
           } */


            var model = new LireModel();
            model.ID = id;
            model.Title = title;
            return View(model);
        }

        //[Route("All"),Route("Tous")]
        //ou bien
        [Route("{Type:regex(All|Tous)}")]
        public ActionResult AllArticles()
        {
            return View();
        }
    }
}

MVC5_ASP_DOT_NET/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC5_ASP_DOT_NET.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC5_ASP_DOT_NET/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC5_ASP_DOT_NET.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

        // GET: Test
        public ActionResult HelloWord()
        {
            return View();
        }
    }
}

MVC5_ASP_DOT_NET/Views/Article/AllArticles.cshtml
@{
    ViewBag.Title = "AllArticles";
}

<h2>AllArticles</h2>

MVC5_ASP_DOT_NET/Views/Article/Lire.cshtml
@model MVC5_ASP_DOT_NET.Models.LireModel

@{
    /**/

    ViewBag.Title = "Lire";

}

<h2>L'article numero @Model.ID</h2>
<h2>Titre de l'article:  @Model.Title</h2>


<!-- http://localhost:50746/Article/Lire/?id=3&title=comment-dev-en-line -->
<!--
    <h2>L'article numero @ViewBag.ArticleId</h2>
    <h2>Titre de l'article: @ViewBag.ArticleTitle</h2>

 -->

MVC5_ASP_DOT_NET/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC5_ASP_DOT_NET/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC5_ASP_DOT_NET/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVC5_ASP_DOT_NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom de l'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("index de Test", "Index", "Test")</li>
                    <li>@Html.ActionLink("HelloWord", "HelloWord", "Test")</li>
                    <li>@Html.ActionLink("Lire Article", "Lire", "Article")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()  //càd la vue correspondante à l'action et controlleur spécifié  (dans le menu en haut) sera afficher içi
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")   //en bas , on inclus les scripts
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)  //permet d'inclure  des sections pour nos scripts ou css ou d'autre chose de ce type là
</body>
</html>

MVC5_ASP_DOT_NET/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html>
<head> 
    <title>@ViewBag.Title </title> 
    @RenderSection("ExternalCSS", false);
</head>
<body>

    <div>
        @RenderBody()
    </div>
    @RenderSection("ExternalJS", false); <!-- section non obliatoire (optionnel) -->
    <!--  RenderSection("TestSectionObliatoireEtNonDefinie", true);  // section obliatoire (true)  donc génère une exception si on ne le met pas  -->
</body>
</html>

MVC5_ASP_DOT_NET/Views/Test/HelloWord.cshtml
@{
    /**/

    ViewBag.Title = "Page Test/HelloWord";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}


@section  ExternalJS
{
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#test").fadeOut(); //çàd  l'element avec id  test , cacher le au chargement de notre page
        });
    </script>

}

@section  ExternalCSS
{
    <style>
        h2 {
            color: red;
        }
    </style>
 }

<h2> @ViewBag.Title </h2>


<p id="test">
    Exemple de Texte
</p>

MVC5_ASP_DOT_NET/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Page Test/Index";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<h2> @ViewBag.Title </h2>